project_id = "hzeoergmlzhdorhgzehz"

[functions.validate-progress]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.manage-instructor]
verify_jwt = true

[functions.create-test-user]
verify_jwt = true