project_id = "hzeoergmlzhdorhgzehz"

[functions.validate-progress]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.process-payment]
verify_jwt = true

[functions.create-test-user]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false