// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzeoergmlzhdorhgzehz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6ZW9lcmdtbHpoZG9yaGd6ZWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDQ4OTcsImV4cCI6MjA3MjYyMDg5N30.EeTNyJENiH3OQGXb5p-P-RzuadAgDYdGtk7qBEnsprs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});